# Generated by Django 3.0.3 on 2020-02-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0002_auto_20200220_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
