# Generated by Django 3.0.3 on 2020-02-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0005_auto_20200220_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Items_images'),
        ),
    ]
