# Generated by Django 3.0.3 on 2020-02-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_app', '0006_auto_20200220_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUID',
        ),
        migrations.AddField(
            model_name='item',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='purchased_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
